services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    networks:
      - app-network
    cpus: "0.10"
    mem_limit: 30m

  app1:
    image: jpplay/rinha-de-backend-2026
    expose:
      - "8080"
    environment:
      - SHARD_ID=0
      - SHARD_COUNT=2
    networks:
      - app-network
    cpus: "0.45"
    mem_limit: 160m

  app2:
    image: jpplay/rinha-de-backend-2026
    expose:
      - "8080"
    environment:
      - SHARD_ID=1
      - SHARD_COUNT=2
    networks:
      - app-network
    cpus: "0.45"
    mem_limit: 160m

networks:
  app-network:
    driver: bridge